# Generated by Django 4.2.4 on 2023-11-14 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cantina', '0004_alter_pedido_cliente_productoencarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cantina.cliente'),
        ),
        migrations.DeleteModel(
            name='ProductoEnCarrito',
        ),
    ]
