# Generated by Django 4.2.4 on 2023-11-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cantina', '0005_alter_pedido_cliente_delete_productoencarrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
