# Generated by Django 4.2.4 on 2023-11-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cantina', '0009_pedido_direccionentrega_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
