# Generated by Django 4.2.4 on 2023-11-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cantina', '0010_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
