# Generated by Django 4.2.4 on 2023-11-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cantina', '0011_remove_cliente_contrasenia_remove_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
