# Generated by Django 4.2.4 on 2023-11-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cantina', '0012_detallepedido_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='carrito',
            field=models.IntegerField(default=0),
        ),
    ]
