# Generated by Django 4.2.4 on 2023-11-16 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cantina', '0013_producto_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(models.IntegerField())]),
            preserve_default=False,
        ),
    ]
