# Generated by Django 4.2.4 on 2023-11-17 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cantina', '0016_producto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='total',
        ),
    ]
