# Generated by Django 4.2.4 on 2023-11-17 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cantina', '0017_remove_detallepedido_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(models.IntegerField())]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='carrito',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
