# Generated by Django 4.2.4 on 2023-11-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cantina', '0018_detallepedido_subtotal_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
